### ISSUE TITLE
Just a reminder. I found google implementation of their own work.

### ISSUE THREAD

**Issue by pengzhenghao** [yl2488/CKA-Centered-kernel-alignment#1]
https://github.com/google-research/google-research/tree/master/representation_similarity

Just a reminder for the author and other potential researchers who looking for CKA implementation.

**Comment by yuanli2333** [comment]
> https://github.com/google-research/google-research/tree/master/representation_similarity
> 
> Just a reminder for the author and other potential researchers who looking for CKA implementation.

Thank you for reminder~
